# Generated at "10:42:54 PM (Sat 20 Dec 2025)"
genome="/project2/noujdine_61/kdeweese/latissima/Assembly/Assembled_scaffolds__masked_/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta.gz"
genome_base="SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked"
genome_local="bams/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta.gz"
genome_local_unzip="bams/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta"
genome_dict="bams/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.dict"
genome_idx="bams/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta.fai"
ht2_idx="bams/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked"
