#######################################
# MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

---
# Title to use for the report.
title: "Saccharina gametophyte WGS QC"

# Disable the analysis paths and time in the report header
show_analysis_paths: False

# Output parsed data directory in addition to the report
data_dir_name: multiqc_data
make_data_dir: True

# Ignore files larger than this when searching for logs (bytes)
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: True

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False # Try to use only flat image graphs
plots_force_interactive: False # Try to use only interactive javascript graphs
plots_flat_numseries: 100 # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50 # If interactive, don't plot on load if > this number of datasets
# max_table_rows: 500 # Swap tables for a beeswarm plot above this

# Customize sample naming
# Force parse log filename (instead of parsing from QC file content)
use_filename_as_sample_name: True
extra_fn_clean_exts:
  # Remove assembly name
  - type: regex
    pattern: "_SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked"
  # Remove any text after a period
  - type: regex
    pattern: "\\..*$"

# Merge samples with distinct read direction & lane numbers
table_sample_merge:
  # Keep only individual ID
  "Individual ID 1":
    - type: regex_keep
      pattern: "S[AL]-[A-Z]{2}-[0-9]{2}-[FM]G-[1-9]{2}"
    - type: regex_keep
      pattern: "S[AL]-[A-Z]{2}-[0-9]-[FM]G-[1-9]{2}"
    - type: regex_keep
      pattern: "S[AL]-[A-Z]{2}-[0-9]{2}-[FM]G-[1-9]"
    - type: regex_keep
      pattern: "S[AL]-[A-Z]{2}-[0-9]-[FM]G-[1-9]"

  # # Library 1 Plate 1
  # "Library 1 Plate 1":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I997_[ATGC]{8}_1_L1$"
  # "Library 1 Plate 1 R1":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I997_[ATGC]{8}_1_L1_R1.*"
  # "Library 1 Plate 1 R2":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I997_[ATGC]{8}_1_L1_R2.*"
  # # Library 2 Plate 1
  # "Library 2 Plate 1":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I997_[ATGC]{8}_1_L1$"
  # "Library 2 Plate 1 R1":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I997_[ATGC]{8}_1_L1_R1.*"
  # "Library 2 Plate 1 R2":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I997_[ATGC]{8}_1_L1_R2.*"
  # # Library 1 Plate 2
  # "Library 1 Plate 2":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1000_[ATGC]{8}_2_L2$"
  # "Library 1 Plate 2 R1":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1000_[ATGC]{8}_2_L2_R1.*"
  # "Library 1 Plate 2 R2":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1000_[ATGC]{8}_2_L2_R2.*"
  # # Library 2 Plate 2
  # "Library 2 Plate 2":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1000_[ATGC]{8}_2_L2$"
  # "Library 2 Plate 2 R1":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1000_[ATGC]{8}_2_L2_R1.*"
  # "Library 2 Plate 2 R2":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1000_[ATGC]{8}_2_L2_R2.*"
  # # Library 1 Plate 3 (Run 1)
  # "Library 1 Plate 3 (Run 1)":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1018_[ATGC]{8}_3_L1$"
  # "Library 1 Plate 3 (Run 1) R1":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1018_[ATGC]{8}_3_L1_R1.*"
  # "Library 1 Plate 3 (Run 1) R2":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1018_[ATGC]{8}_3_L1_R2.*"
  # # Library 2 Plate 3 (Run 1)
  # "Library 2 Plate 3 (Run 1)":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1018_[ATGC]{8}_3_L1$"
  # "Library 2 Plate 3 (Run 1) R1":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1018_[ATGC]{8}_3_L1_R1.*"
  # "Library 2 Plate 3 (Run 1) R2":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1018_[ATGC]{8}_3_L1_R2.*"
  # # Library 1 Plate 3 (Run 2)
  # "Library 1 Plate 3 (Run 2)":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1019_[ATGC]{8}_3_L1$"
  # "Library 1 Plate 3 (Run 2) R1":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1019_[ATGC]{8}_3_L1_R1.*"
  # "Library 1 Plate 3 (Run 2) R2":
  #   - type: regex
  #     pattern: "^I[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1019_[ATGC]{8}_3_L1_R2.*"
  # # Library 2 Plate 3 (Run 2)
  # "Library 2 Plate 3 (Run 2)":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1019_[ATGC]{8}_3_L1$"
  # "Library 2 Plate 3 (Run 2) R1":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1019_[ATGC]{8}_3_L1_R1.*"
  # "Library 2 Plate 3 (Run 2) R2":
  #   - type: regex
  #     pattern: "^J[A-Z]{3}_"
  #   - type: regex
  #     pattern: "_I1019_[ATGC]{8}_3_L1_R2.*"

# # Prevent picard/markdups from overwriting stats for samples with multiple libraries
# picard_config:
#   markdups_merge_multiple_libraries: False

# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
sp:
  hisat2:
    fn: "*.hisat2.summary"
  picard/markdups:
    fn: "*.marked_dup_metrics.txt"
  picard/alignment_metrics:
    fn: "*.alignment_summary_metrics.txt"
  picard/basedistributionbycycle:
    skip: true
  picard/gcbias:
    skip: true
  picard/hsmetrics:
    skip: true
  picard/insertsize:
    fn: "*.insert_size_metrics.txt"
  picard/oxogmetrics:
    skip: true
  picard/pcr_metrics:
    skip: true
  picard/quality_by_cycle:
    skip: true
  picard/quality_score_distribution:
    skip: true
  picard/quality_yield_metrics:
    fn: "*.quality_yield_metrics.txt"
  picard/rnaseqmetrics:
    skip: true
  picard/rrbs_metrics:
    skip: true
  picard/sam_file_validation:
    # fn: "*.validate.summary"
    skip: true
  picard/variant_calling_metrics:
    skip: true
  picard/wgs_metrics:
    fn: "*.collect_wgs_metrics.txt"
  samtools/stats:
    fn: "*.stats"
  gatk/varianteval:
    fn: "*.variant_eval.txt"
  bcftools/stats:
    fn: "*.bcftools.stats"

# Change module order
module_order:
  - bcftools/stats
  - gatk/varianteval
  - samtools/stats
  - picard/alignment_metrics
  - picard/insertsize
  - picard/quality_yield_metrics
  - picard/wgs_metrics
  - picard/markdups
  - hisat2
  # - picard/sam_file_validation
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results AFTER adapter trimming."
      target: ""
      path_filters:
        - "*val_1_fastqc.zip"
        - "*val_2_fastqc.zip"
  - cutadapt
  - fastqc:
      name: "FastQC (raw)"
      info: "This section of the report shows FastQC results BEFORE adapter trimming."
      anchor: "fastqc_raw"
      path_filters:
        - "*_R1_fastqc.zip"
        - "*_R2_fastqc.zip"

