#######################################
# Example MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

---
# Title to use for the report.
title: "S. latissima gametophyte WGS QC"

# Disable the analysis paths and time in the report header
show_analysis_paths: False
show_analysis_time: False

# Output filenames
output_fn_name: multiqc_report.html
data_dir_name: multiqc_data

# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Ignore files larger than this when searching for logs (bytes)
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: True

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False # Try to use only flat image graphs
plots_force_interactive: False # Try to use only interactive javascript graphs
plots_flat_numseries: 100 # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50 # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500 # Swap tables for a beeswarm plot above this


# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
sp:
  hisat2:
    fn: "*.hisat2.summary"
  picard/markdups:
    fn: "*.mark_dupes.metrics"
  picard/alignment_metrics:
    fn: "*.collect_alignment_summary.metrics"
  picard/basedistributionbycycle:
    skip: true
  picard/gcbias:
    skip: true
  picard/hsmetrics:
    skip: true
  picard/insertsize:
    skip: true
  picard/oxogmetrics:
    skip: true
  picard/pcr_metrics:
    skip: true
  picard/quality_by_cycle:
    skip: true
  picard/quality_score_distribution:
    skip: true
  picard/quality_yield_metrics:
    skip: true
  picard/rnaseqmetrics:
    skip: true
  picard/rrbs_metrics:
    skip: true
  picard/sam_file_validation:
    fn: "*.validate.summary"
  picard/variant_calling_metrics:
    skip: true
  picard/wgs_metrics:
    fn: "*.collect_wgs.metrics"

# Change module order
module_order:
  - picard/markdups
  - picard/alignment_metrics
  - picard/wgs_metrics
  - hisat2
  - picard/sam_file_validation
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results AFTER adapter trimming."
      target: ""
      path_filters:
        - "*val_1_fastqc.zip"
  - cutadapt
  - fastqc:
      name: "FastQC (raw)"
      info: "This section of the report shows FastQC results BEFORE adapter trimming."
      anchor: "fastqc_raw"
      path_filters:
        - "*_R1_fastqc.zip"

