# Pipeline variables
# Set sleep time (wait time) between checking for checkpoints
sleep_time=1800

# Directory to copy reads into
samples_dir="wgs"
# Directory to write array-indexed lists (e.g., $samples_list)
indexer_dir="indexer"
# Text file listing sample IDs
samples_list="$indexer_dir/samples_list.txt"
# Directory to write QC output
qc_dir="quality_control"
# Directory to write trimmed read files
trimmed_dir="trimmed_reads"
# Directory to write BAM files
bams_dir="bams"
# Directory to write parsed data for MultiQC
multiqc_dir="multiqc_data"
# Text file listing individual IDs
indiv_list="$indexer_dir/individuals_file.txt"
# Directory to write gVCFs
gvcfs_dir="gvcfs"
# Directory to write inverval.list files (output of GATK4's SplitIntervals)
split_intervals_dir="split_intervals"
# Target number of interval_lists to split into for scatter-gather parallelization
scatter=100
# Text file listing interval.list filenames
intervals_list="$indexer_dir/intervals_list.txt"
# Text file listing gVCF filenames
gvcf_list="$indexer_dir/gvcfs.list"
# Directory to import gVCFs into GenomicsDBs
genomicsdbimport_dir="genomicsdbimport"
# Directory to write genotyped VCFs
vcfs_dir="vcfs"
# Text file listing genotyped VCF filenames
vcf_list="$indexer_dir/vcf.list"