# User-defined input variables
# Reference genome
genome="/project2/noujdine_61/kdeweese/latissima/Assembly/Assembled_scaffolds__masked_/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta.gz"
# Path to folder containing raw reads
# Pipeline assumes compressed FASTQs with extension: ".fastq.gz"
path_to_raw_reads="/project2/noujdine_61/sugar_kelp_data/all_wgs/"
# Slurm partition for sbatch submissions
partition="main"