#!/bin/bash
#SBATCH -p gpu
#SBATCH --time=3-0
#SBATCH -J queen
#SBATCH -o %x.log

## Variant calling pipeline
# A SLURM- and conda-dependent pipeline with sequential job steps linked by 
# dependencies and checkpoint files

# Help message
if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]
then
    echo "\
----------------------WELCOME TO VARIANT CALLING PIPELINER----------------------

Usage: 
  sbatch pipeline_template.sh [options] <path/to/reference/genome> <path/to/dir/
containing/FASTQs> <partition> [scripts_dir]

Options:
  -h/--help                      print this usage message

Note: Sourced SBATCH files named with convention: <prefix>.sbatch 

Takes as input a genome and PATH to a directory containing FASTQs to align, and
outputs...

Analysis:
  indexer/
    samples_file.txt             indexes sample IDs
    individuals_file.txt         indexes individual IDs
    intervals_file.txt           indexes split interval lists
    gvcf.list                    indexes gVCF files 
    vcf.list                     indexes VCF files (in numerical order)
  wgs/                        
    *.fastq.gz                   FASTQ files renamed to shorter sample IDs 
                                 (copied from source)
    *.repaired.fastq.gz          FASTQ read pairs repaired with repair.sh
  trimmed_reads/
    *_val_1/2.fq.gz              reads post trimming by Trim Galore!
  bams/
    *.fasta                      reference genome (copied from source)
    *.fasta.ht2                  indexed reference genome
    *.fasta.fai                  samtools-indexed reference genome
    *.dict                       GATK4-style reference genome dictionary
    *.sorted.bam                 sorted alignment files of trimmed reads to 
                                 reference genome
    *.sorted.marked.bam          sorted alignment files, duplicates marked
    *.sorted.marked.merged.bam   sorted alignment files, merged by individual
  gvcfs/
    *.g.vcf.gz                   genome variant call files (gVCFs) for each 
                                 individual
  split_intervals/
    *-scattered.interval_list    GATK4-style lists of genomic intervals, split 
                                 into as close to the desired scatter count as 
                                 possible without splitting input reference 
                                 contigs (e.g., scaffolds/chromosomes)
  genomicsdbimport/
    interval_*/                  GATK4-style GenomicsDB (datastore of variant
                                 call data from each individual, split into 
                                 groups of genomic intervals specified in 
                                 *-scattered.interval_list files)
  vcfs/
    *.vcf.gz                     variant call files (VCFs) for each group of 
                                 genomic intervals
  master_{genome_base}.vcf.gz    final VCF file of all samples aligned to the
                                 reference genome

Quality control:
  quality_control/
    *_fastqc.zip/html            FastQC reports for all input FASTQs
    *_val_1/2_fastqc.zip/html    FASTQC reports for trimmed FASTQs
    *_trimming_report.txt        Trim Galore! trimming report for each sample
    *.hisat2.summary             HISAT2 alignment report for each sample
    *.validate.summary           validation reports of alignment (SAM/BAM) and 
                                 variant (gVCF/VCF) files
    multiqc_report.html          MultiQC report summarizing QCs at each step

Logs and checkpoints:
  queen.log                      log file generated by pipeliner script
  <prefix>_logs/
    <prefix>_<#>.out             SLURM log files from inividual job step 
                                 submissions, named with the convention: 
                                 <prefix>.sbatch > 
                                 <prefix>_logs/<prefix>_<#>.out 2>&1
                                 created upon job completion, where #
                                 corresponds to array index of <prefix> job step
  checkpoints/
    <prefix>_<#>.checkpoint      checkpoint file(s) for each job step, named 
                                 with the convention: 
                                 <prefix>.sbatch == <prefix>_<#>.checkpoint
                                 created upon job completion, where # 
                                 corresponds to array index of <prefix> job step

Temporary directories:
  <prefix>_tmp                   temporary directory for a given job step

Direct any questions to Kelly DeWeese (kdeweese@mac.com)
"
    exit 0
fi


# Define global variables
# Master log file
pipeline_log="queen.log"
# User defined
# genome="$1"
genome="/project2/noujdine_61/kdeweese/latissima/Assembly/Assembled_scaffolds__masked_/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta.gz"
# path_to_raw_reads="$2"
path_to_raw_reads="/project2/noujdine_61/sugar_kelp_data/all_wgs/"
# partition="$3"
partition="gpu"
# Optional, directory containing scripts
# scripts_dir="$4"
scripts_dir="s-latissima-popgen"

# Validate and parse global variables
# If genome file exists, change name to realpath
if [[ -f "$genome" ]] 
then
    genome="$(realpath -e "$genome")"
else
    echo "Genome file $genome not detected." >> "$pipeline_log"
    exit 1
fi
genome_basename="$(basename "$genome")"
genome_basename_unzip="${genome_basename%%.gz}"
genome_base="${genome_basename%%.*}"
# If path to raw reads exists, change name to realpath
if [[ -d "$path_to_raw_reads" ]]
then
    path_to_raw_reads="$(realpath -e "$path_to_raw_reads")"
else
    echo "Reads directory ($path_to_raw_reads) not detected." >> "$pipeline_log"
    exit 1
fi
# If scripts directory is speicified and exists, change to realpath and append 
# '/' to name
if [[ "$scripts_dir" ]] && [[ -d "$scripts_dir" ]]
then
    scripts_dir="$(realpath -e "$scripts_dir")"
    scripts_dir="$scripts_dir/"
    echo "Path to scripts: ${scripts_dir}..." >> "$pipeline_log"
else
    echo "Path to scripts: $(pwd) (current directory)" >> "$pipeline_log"
fi

# Pipeline variables
# Assumes paired-end FASTQs
num_fastqs="$(find "$path_to_raw_reads" -mindepth 2 -maxdepth 2 \
    -type f -name "*.fastq.gz" -exec realpath -e {} \; | wc -l)"
num_samples="$(( num_fastqs / 2 ))"
indexer_dir="indexer"
mkdir -p "$indexer_dir"
samples_dir="wgs"
samples_file="$indexer_dir/samples_file.txt"
qc_dir="quality_control"
mkdir -p "$qc_dir"
trimmed_dir="trimmed_reads"
mkdir -p "$trimmed_dir"
bams_dir="bams"
mkdir -p "$bams_dir"
indiv_file="$indexer_dir/individuals_file.txt"
gvcfs_dir="gvcfs"
mkdir -p "$gvcfs_dir"
split_intervals_dir="split_intervals"
mkdir -p "$split_intervals_dir"
# Number of interval groups to split into for scatter-gather parallelization
scatter="100"
intervals_file="intervals_file.txt"
gvcf_list="$indexer_dir/gvcfs.list"
genomicsdbimport_dir="genomicsdbimport"
mkdir -p "$genomicsdbimport_dir"
vcf_list="$indexer_dir/vcf.list"
vcfs_dir="vcfs"
mkdir -p "$vcfs_dir"

# Functions
# Define function to return prefix of input file
get_prefix () {
    local filename
    filename="$(basename "$1")"
    filename="${filename%.*}"
    echo "$filename"
}
# Define function to make a log directory from an input string
# (e.g., prefix) only if it doesn't already exist
make_logdir () {
    # Create log directory (if needed) from given prefix
    local logdir
    logdir="${1}_logs"
    mkdir -p "$logdir"
    echo "$logdir"
}
# Define function for array or non-array submission
# that returns the jobid but takes no dependencies
no_depend () {
    local array_size
    local sbatch_file
    local prefix
    local trailing_args
    local logdir
    local jobid
    local cmd
    # Define job type
    # Determine array size for all batch jobs (e.g., number of samples)
    if [[ "$1" = "--array" ]]
    then
        # Inputs
        array_size="$2"
        if [[ $(echo "$array_size" | sed 's/,/ /g' | wc -w) -eq 1 ]]
        then
            array_size="1-${array_size}"
        fi
        sbatch_file="$3"
        prefix="$4"
        trailing_args=( "${@:5}" )
        # Create log directory named after prefix
        logdir="$(make_logdir "$prefix")"
        # Job submission
        cmd=(
            sbatch
            --parsable
            -p "$partition"
            -J "$prefix"
            --array="$array_size"
            -o "$logdir/%x_%a.out"
            "$sbatch_file"
            "$prefix"
            "${trailing_args[@]}"
        )
        jobid="$("${cmd[@]}")"
        echo "${cmd[*]}" >> "$pipeline_log"
    else
        # Inputs
        sbatch_file="$1"
        prefix="$2"
        trailing_args=( "${@:3}" )
        # Create log directory named after prefix
        logdir="$(make_logdir "$prefix")"
        # Job submission
        cmd=(
            sbatch
            --parsable
            -p "$partition"
            -J "$prefix"
            -o "$logdir/%x_%j.out"
            "$sbatch_file"
            "$prefix"
            "${trailing_args[@]}"
        )
        jobid="$("${cmd[@]}")"
        echo "${cmd[*]}" >> "$pipeline_log"
    fi
    echo "$jobid"
}
# Define function for array or non-array submission
# that takes a dependency and returns a jobid
depend () {
    local array_size
    local sbatch_file
    local prefix
    local dep_jobid
    local trailing_args
    local logdir
    local jobid
    local cmd
    # Define job type
    if [[ "$1" = "--array" ]]
    then
        # Inputs
        array_size="$2"
        if [[ $(echo "$array_size" | sed 's/,/ /g' | wc -w) -eq 1 ]]
        then
            array_size="1-${array_size}"
        fi
        sbatch_file="$3"
        prefix="$4"
        dep_jobid="$5"
        trailing_args=( "${@:6}" )
        # Create log directory named after prefix
        logdir="$(make_logdir "$prefix")"
        # Job submission
        cmd=(
            sbatch
            --parsable
            -p "$partition"
            -J "$prefix"
            --array="$array_size"
            -o "$logdir/%x_%a.out"
            --dependency="afterok:$dep_jobid"
            "$sbatch_file"
            "$prefix"
            "${trailing_args[@]}"
        )
        jobid="$("${cmd[@]}")"
        echo "${cmd[*]}" >> "$pipeline_log"
    else
        # Inputs
        sbatch_file="$1"
        prefix="$2"
        dep_jobid="$3"
        trailing_args=( "${@:4}" )
        # Create log directory named after prefix
        logdir="$(make_logdir "$prefix")"
        # Job submission
        cmd=(
            sbatch
            --parsable
            -p "$partition"
            -J "$prefix"
            -o "$logdir/%x_%j.out"
            --dependency="afterok:$dep_jobid"
            "$sbatch_file"
            "$prefix"
            "${trailing_args[@]}"
        )
        jobid="$("${cmd[@]}")"
        echo "${cmd[*]}" >> "$pipeline_log"
    fi
    echo "$jobid"
}
# Define function to list checkpoint files based on given prefix
ls_check () {
    local prefix
    prefix="$1"
    if [[ -z "$prefix" ]]
    then
        {
            date
            echo "Error - no prefix given to 'ls_check'." >> "$pipeline_log"
        }
        exit 1
    fi
    find checkpoints -type f -name "$prefix*.checkpoint"
}
# Define function to check for and remove checkpoint files with same prefix
rm_check () {
    local prefix
    prefix="$1"
    find checkpoints -type f -name "$prefix*.checkpoint" -delete
}
# Define function to check for checkpoint files by prefix and
# return array of missing array indices (compared with array size)
miss_check () {
    local prefix
    local array_size
    prefix="$1"
    array_size="$2"
    if [[ -n "$(ls_check "$prefix")" ]]
    then
        for i in $(seq "$array_size")
        do
            if [[ ! -f "checkpoints/${prefix}_${i}.checkpoint" ]]
            then
                printf "%s," "$i"
            fi
        done
    else
        echo "Error - no checkpoints found for step: $prefix" >> "$pipeline_log"
        exit 1
    fi
}
# Define function to run an array job step with a set number of 
# checkpoints files as a "dependency" (e.g., wait steps)
# (This avoids QOSMax errors from SLURM with next to zero use of storage)
pipeliner () {
    local array_indices
    local dependency_prefix
    local dependency_size
    local sleep_time
    local input_sbatch
    local input_prefix
    local trailing_args
    local num_checks
    local array_flag
    local jobid
    if [[ "$1" = "--array" ]]
    then
        array_indices="$2"
        dependency_prefix="$3"
        dependency_size="$4"
        sleep_time="$5"
        input_sbatch="$6"
        input_prefix="$7"
        trailing_args=( "${@:8}" )
    else
        dependency_prefix="$1"
        dependency_size="$2"
        sleep_time="$3"
        input_sbatch="$4"
        input_prefix="$5"
        trailing_args=( "${@:6}" )
    fi
    if [ $# -eq 0 ]
    then
        echo "Error - no input to 'pipeliner'. Exiting..." >> "$pipeline_log"
        exit 1
    fi
    echo "pipeliner $*" >> "$pipeline_log"
    until [[ "$(ls_check "$dependency_prefix" | wc -l)" -eq "$dependency_size" ]]
    do
        {
            date
            echo "Waiting for completion of $dependency_prefix step."
        } >> "$pipeline_log"
        sleep "$sleep_time"
    done
    if [[ -n "$(ls_check "$input_prefix")" ]]
    then
        num_checks="$(ls_check "${input_prefix}" | wc -l)"
        {
            date
            echo "$num_checks checkpoint(s) detected for $input_prefix"
            echo "Validating..."
        } >> "$pipeline_log"
        if [[ "$1" = "--array" ]] && \
           [[ -n "$array_indices" ]] && \
           [[ "$num_checks" -ne "$array_indices" ]] 
        then
            array_flag=(
                "$1"
                "$(miss_check "$input_prefix" "$array_indices")"
            )
            {
                echo "Error detected in $input_prefix checkpoint. Restarting."
                echo "Submitting job array indices: $array_indices"
            } >> "$pipeline_log"
            jobid="$(no_depend "${array_flag[@]}" "$input_sbatch" "$input_prefix" \
                "${trailing_args[@]}")"
        elif [[ "$num_checks" -eq "$array_indices" ]]
        then
            echo "$input_prefix step already run. Skipping." >> "$pipeline_log"
        elif [[ "$1" != "--array" ]] && [[ "$num_checks" -eq 1 ]]
        then
            echo "$input_prefix step already run. Skipping." >> "$pipeline_log"
        else
            echo "Error - check inputs to 'pipeliner'." >> "$pipeline_log"
        fi
    else
        if [[ "$1" = "--array" ]] && [[ -n "$array_indices" ]]
        then
            array_flag=(
                "$1"
                "$array_indices"
            )
        fi
        echo "Beginning $input_prefix step." >> "$pipeline_log"
        jobid="$(no_depend "${array_flag[@]}" "$input_sbatch" "$input_prefix" \
            "${trailing_args[@]}")"
    fi
    echo "$jobid"
}

# Run pipeline
# Set array size for working with sample IDs
array_size="$num_samples"
{
    date
    echo "Array size set to: $array_size"
    echo
}>> "$pipeline_log"

# Set sleep time (wait time) between checking for checkpoints
sleep_time=1800
if (( $(( sleep_time / 60 )) < 1 ))
then
    st="$(( sleep_time / 60 )) second(s)"
elif (( $(( sleep_time / 3600 )) > 1 ))
then
    hr="$(( sleep_time / 3660 ))"
    min="$(( (sleep_time - (hr * 3600)) / 60 ))"
    st="$hr hour(s) and $min minute(s)"
else
    st="$(( sleep_time / 60 )) minute(s)"
fi
{
    date
    echo "Wait time between checking for checkpoints set to: $st"
    echo
} >> "$pipeline_log"

# Rename reads and create $samples_file
input_sbatch="${scripts_dir}rename.sbatch"
input_prefix="$(get_prefix "$input_sbatch")"
# Before running, check if run has already succeeded
if [[ -f "$samples_file" ]] && [[ -n "$(ls_check "$input_prefix")" ]]
then
    {
        date
        echo "Checkpoint and samples file ($samples_file) detected."
        echo "Skipping step: $input_prefix"
    } >> "$pipeline_log"
else
    rm_check "$input_prefix"
    {
        date >> "$pipeline_log" 
        echo "Copying FASTQs from: $path_to_raw_reads"
        echo "Renamed FASTQs will be in: $samples_dir"
    } >> "$pipeline_log" 
    jobid="$(no_depend "$input_sbatch" "$input_prefix" "$path_to_raw_reads" \
        "$samples_dir" "$samples_file" "$scripts_dir")"
fi
# Set dependency size for next step
dependency_size=1
echo >> "$pipeline_log"

# # Remove original renamed reads to conserve memory before next steps
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# input_prefix="og_reads_deleted"
# if [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# then
#     if [[ -n "$(ls_check "$prefix")" ]]
#     then
#         { 
#             date
#             echo "Renamed reads already removed. Skipping."
#         } >> "$pipeline_log"
#     else    
#         { 
#             date
#             echo "Removing renamed reads to conserve memory before next steps."
#         } >> "$pipeline_log"
#         while IFS= read -r sample_id
#         do
#             if [[ -f "$samples_dir/${sample_id}_R1.fastq.gz" ]] && \
#                [[ -f "$samples_dir/${sample_id}_R2.fastq.gz" ]] && \
#                [[ -f "$trimmed_dir/${sample_id}_R1.repaired.fastq.gz" ]] && \
#                [[ -f "$trimmed_dir/${sample_id}_R2.repaired.fastq.gz" ]]
#             then
#                 rm "$samples_dir/${sample_id}_R1.fastq.gz"
#                 rm "$samples_dir/${sample_id}_R2.fastq.gz"
#             else
#                 {
#                     date
#                     echo "Error - some reads missing for ${sample_id}."
#                     echo "No checkpoint file detected for step: $input_prefix"
#                 } >> "$pipeline_log"
#                 exit 1
#             fi
#         done < "$samples_file"
#         touch "checkpoints/${input_prefix}.checkpoint"
#     fi
# fi
# echo >> "$pipeline_log"

# FastQC
# Keep previous dependency
dependency_prefix="$input_prefix"
dependency="$jobid"
input_sbatch="${scripts_dir}fastqc.sbatch"
input_prefix="$(get_prefix "$input_sbatch")"
# Check for dependency jobid
if [[ -n "$dependency" ]]
then
    {
        date
        echo "Running $input_prefix after $dependency_prefix step"
        echo "($dependency_prefix job ID: $dependency)"
    } >> "$pipeline_log"
    jobid="$(depend --array "$array_size" \
        "$input_sbatch" "$input_prefix" "$dependency" \
        "$samples_dir" "$qc_dir" \
        "$samples_file")"
else
    # If dependency is finished running, verify its checkpoint
    jobid="$(pipeliner --array "$array_size" \
        "$dependency_prefix" $dependency_size \
        "$sleep_time" "$input_sbatch" "$input_prefix" \
        "$samples_dir" "$qc_dir" \
        "$samples_file")"
fi
# Set dependency size for next step
dependency_size="$array_size"
echo >> "$pipeline_log"

# # Quality and adapter trimming
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}trim_galore.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" $dependency_size \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$samples_dir" "$qc_dir" \
#     "$samples_file" "$trimmed_dir")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run HISAT2-build on genome
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}build_hisat2.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner \
#     "$dependency_prefix" $dependency_size \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome")"
# dependency_size=1
# echo >> "$pipeline_log"

# # Redefine $genome location after HISAT2-build step
# if [[ -f "$bams_dir/$genome_basename_unzip" ]]
# then
#     genome="$bams_dir/$genome_basename_unzip"
#     {
#         date
#         echo "Genome now being sourced from: $genome"
#     } >> "$pipeline_log"
# else
#     {
#         date
#         echo "Error - gunzipped genome not detected in $bams_dir"
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Run HISAT2 on all samples
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}hisat2.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$trimmed_dir" "$bams_dir" \
#     "$genome" "$samples_file" "$qc_dir" "$indiv_file")"
# dependency_size="$array_size"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Sort IDs in $indiv_file for unique invidual IDs
# dependency_prefix="$input_prefix"
# until [[ -f "$indiv_file" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     date >> "$pipeline_log"
#     echo "Waiting for completion of $dependency_prefix step." >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# if [[ -f "$indiv_file" ]]
# then
#     date
#     echo "Sorting $indiv_file for unique invidual IDs." >> "$pipeline_log"
#     sort -u "$indiv_file" > "${indiv_file}_sorted"
#     mv "${indiv_file}_sorted" "$indiv_file"
# else
#     {
#         date
#         echo "Error - invidual ID file ($indiv_file) not detected."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Create reference genome dictionary and 
# # samtools index of genome for GATK tools
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}prep_ref.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # Run GATK4 ValidateSamFile on HISAT2 alignmnet BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_sams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# pattern=".sorted.bam"
# iteration=1
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_file" "$pattern")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 CollectAlignmentSummaryMetrics 
# # on HISAT2 alignmnet BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}collect_alignment_summary_metrics.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_file")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 CollectWgsMetrics on HISAT2 alignmnet BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}collect_wgs_metrics.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_file")"
# echo >> "$pipeline_log"

# # Run GATK4 MarkDuplicates
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}mark_dupes.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome" "$samples_file" "$qc_dir")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 ValidateSamFile on MarkDuplicate BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_sams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# pattern=".marked.sorted.bam"
# iteration=2
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_file" "$pattern")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Set new array size to number of individuals
# if [[ -f "$indiv_file" ]]
# then
#     num_indiv="$(wc -l < "$indiv_file")"
#     array_size="$num_indiv"
#     {
#         date
#         echo "Array size set to ${array_size}."
#     } >> "$pipeline_log"
# else
#     { 
#         date
#         echo "Error - invidual ID file ($indiv_file) not detected."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Collapse BAMs per sample into BAMs per individual with GATK4 MergeSamFiles
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}collapse_bams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome" "$indiv_file")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 ValidateSamFile on MarkDuplicate BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_sams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# pattern=".merged.marked.sorted.bam"
# iteration=3
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$indiv_file" "$pattern")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Index collapsed BAMs for GATK4 HaplotypeCaller
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}index_bams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome" "$indiv_file")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 HaplotypeCaller
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}haplotype_caller.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$gvcfs_dir" \
#     "$genome" "$indiv_file")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Create file to index HaplotypeCaller gVCFs
# dependency_prefix="$input_prefix"
# until [[ -d "$gvcfs_dir" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     date >> "$pipeline_log"
#     echo "Waiting for completion of $dependency_prefix step." >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# num_gvcfs="$(find "$gvcfs_dir" -type f -name "*.g.vcf.gz" | wc -l)"
# if [[ "$num_gvcfs" -eq "$array_size" ]]
# then
#     {
#         date
#         echo "Creating $gvcf_list of $num_gvcfs files."
#     } >> "$pipeline_log"
#     find "$gvcfs_dir" -type f -name "*.g.vcf.gz" > "$gvcf_list"
#     num_gvcfs_list="$(wc -l < "$gvcf_list")"
#     if [[ $num_gvcfs_list -ne $array_size ]]
#     then
#         {
#             date
#             echo "Error - incorrect # files ($num_gvcfs_list/$array_size) in $gvcf_list"
#             echo "Exiting..."
#         } >> "$pipeline_log"
#         exit 1
#     fi
# else
#     {
#         date
#         echo "Error - incorrect # files ($num_gvcfs/$array_size) in $gvcfs_dir"
#         echo "$gvcf_list not created. Exiting..."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Run GATK4 ValidateVariants on HaplotypeCaller gVCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_variants.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# iteration=1
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$gvcfs_dir" "$qc_dir" \
#     "$genome" "$gvcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 SplitIntervals on genome to produce interval 
# # lists in $split_intervals_dir for CombineGVCFs step
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}split_intervals.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$split_intervals_dir" "$split_intervals_dir" \
#     "$genome" "$scatter")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # Set array size to number of split interval lists created
# dependency_prefix="$input_prefix"
# until [[ -d "$split_intervals_dir" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     {
#         date
#         echo "Waiting for completion of $dependency_prefix step."
#     } >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# array_size="$(find "$split_intervals_dir" -type f -name "*.list" | wc -l)"
# {
#     date
#     echo "Array size set to number of split interval lists ($array_size) created
#     by split_intervals step (not necessarily equal to scatter=$scatter because
# --subdivision-mode BALANCING_WITHOUT_INTERVAL_SUBDIVISION)."
# } >> "$pipeline_log"
# # Create file to index split intervals lists
# find "$split_intervals_dir" -type f -name "*.list" > "$intervals_file"
# echo >> "$pipeline_log"

# # Run GATK4 GenomicsDBImport
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}genomicsdbimport.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$gvcfs_dir" "$genomicsdbimport_dir" \
#     "$genome" "$intervals_file" "$gvcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 GenotypeGVCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}genotype_gvcfs.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$genomicsdbimport_dir" "$vcfs_dir" \
#     "$genome")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Create list of GenotypeGVCFs VCFs
# dependency_prefix="$input_prefix"
# until [[ -d "$vcfs_dir" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     {
#         date
#         echo "Waiting for completion of $dependency_prefix step."
#     } >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# num_vcfs="$(find $vcfs_dir -type f -name "*${genome_base}.vcf.gz" | wc -l)"
# if [[ "$num_vcfs" -eq "$array_size" ]]
# then
#     {
#         date
#         echo "Creating $vcf_list of $num_vcfs files."
#     } >> "$pipeline_log"
#     find $vcfs_dir -type f -name "*${genome_base}.vcf.gz" > "$vcf_list"
#     num_vcfs_list="$(wc -l < "$vcf_list")"
#     if [[ "$num_vcfs_list" -ne "$array_size" ]]
#     then
        
#         {
#             date
#             echo "Error - incorrect # files ($num_vcfs_list/$array_size) in $vcf_list" 
#             echo "Exiting..."
#         } >> "$pipeline_log"
#         exit 1
#     fi
# else
#     {
#         date
#         echo "Error - incorrect # files ($num_vcfs/$array_size) in $vcfs_dir"
#         echo "$vcf_list not updated. Exiting..."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Run GATK4 SortVcf on GenotypeGVCFs VCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}sort_vcf.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$vcfs_dir" "$qc_dir" \
#     "$genome" "$vcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Overwrite index of VCF files with sorted index
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# until [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     {
#         date
#         echo "Waiting for completion of $dependency_prefix step."
#     } >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# num_vcfs="$(find $vcfs_dir -type f -name "*${genome_base}sorted.vcf.gz" | wc -l)"
# if [[ "$num_vcfs" -eq "$array_size" ]]
# then
#     {
#         date
#         echo "Creating $vcf_list of $num_vcfs files."
#     } >> "$pipeline_log"
#     ls "$vcfs_dir/"*"${genome_base}.sorted.vcf.gz" > "$vcf_list"
#     num_vcfs_list="$(wc -l < "$vcf_list")"
#     if [[ "$num_vcfs_list" -ne "$array_size" ]]
#     then
#         {
#             date
#             echo "Error - incorrect # files ($num_vcfs_list/$array_size) in $vcf_list"
#             echo "Exiting..."
#         } >> "$pipeline_log"
#         exit 1
#     fi
# else
#     {
#         date
#         echo "Error - incorrect # files ($num_vcfs/$array_size) in $vcfs_dir"
#         echo "$vcf_list not updated. Exiting..."
#     } >> "$pipeline_log"
# fi
# echo >> "$pipeline_log"

# # Run GATK4 ValidateVariants on GenotypeGVCFs VCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_variants.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# iteration=2
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$vcfs_dir" "$qc_dir" \
#     "$genome" "$vcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 MergeVcfs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}merge_vcfs.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$vcfs_dir" "$genome" "$vcf_list")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # Run MultiQC on pipeline QC outputs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}multiqc.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# if [[ -n "$dependency" ]]
# then
#     {
#         date
#         echo "Running $input_prefix after $dependency_prefix step (jobid: $dependency)" 
#     } >> "$pipeline_log"
#     jobid="$(depend "$input_sbatch" "$input_prefix" \
#         "$dependency" \
#         "$qc_dir" "$scripts_dir")"
# fi
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$qc_dir" "$scripts_dir")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

