#!/bin/bash
#SBATCH --time=2-0
#SBATCH -J queen
#SBATCH -o %x.log

## Variant calling pipeline
# A SLURM- and conda-dependent pipeline with sequential job steps linked by 
# dependencies and checkpoint files

# Help message
if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]
then
    echo "\
----------------------WELCOME TO VARIANT CALLING PIPELINER----------------------

Usage: 
  bash/sbatch pipeline-s-latissima-popgen.sh [scripts_dir]

Options:
  -h/--help                      print this usage message

Note: Sourced SBATCH files named with convention: <prefix>.sbatch 

Takes as input a genome and PATH to a directory containing FASTQs to align, and
outputs...

Analysis:
  indexer/
    samples_list.txt            indexes sample IDs
    individuals_file.txt        indexes individual IDs
    intervals_list.txt          indexes split interval lists
    gvcf.list                   indexes gVCF files 
    vcf.list                    indexes VCF files (in numerical order)
  wgs/                        
    *.fastq.gz                  FASTQ files renamed to shorter sample IDs 
                                (copied from source)
  trimmed_reads/
    *_val_1/2.fq.gz             reads post trimming by Trim Galore!
  bams/
    *.fasta                     reference genome (copied from source)
    *.fasta.ht2                 indexed reference genome
    *.fasta.fai                 samtools-indexed reference genome
    *.dict                      GATK4-style reference genome dictionary
    *.sorted.bam                sorted alignment files of trimmed reads to 
                                reference genome
    *.sorted.marked.bam         sorted alignment files, duplicates marked
    *.sorted.marked.merged.bam  sorted alignment files, merged by individual
  gvcfs/
    *.g.vcf.gz                  genome variant call files (gVCFs) for each
                                individual
  split_intervals/
    *-scattered.interval_list   GATK4-style lists of genomic intervals, split 
                                into as close to the desired scatter count as 
                                possible without splitting input reference 
                                contigs (e.g., scaffolds/chromosomes)
  genomicsdbimport/
    interval_*/                 GATK4-style GenomicsDB (datastore of variant
                                call data from each individual, split into 
                                groups of genomic intervals specified in 
                                *-scattered.interval_list files)
  vcfs/
    *.vcf.gz                    variant call files (VCFs) for each group of 
                                genomic intervals
  master_{genome_base}.vcf.gz   final VCF file of all samples aligned to the
                                reference genome

Quality control:
  quality_control/
    *_fastqc.zip/html           FastQC reports for all input FASTQs
    *_val_1/2_fastqc.zip/html   FASTQC reports for trimmed FASTQs
    *_trimming_report.txt       Trim Galore! trimming report for each sample
    *.hisat2.summary            HISAT2 alignment report for each sample
    *.validate.summary          validation reports of alignment (SAM/BAM) and 
                                variant (gVCF/VCF) files
    multiqc_report.html         MultiQC report summarizing QCs at each step

Logs and checkpoints:
  queen.log                     log file generated by pipeliner script
  <prefix>.log                  Slurm log files from single job steps
  <prefix>_logs/
    <prefix>_<array_#>.log      Slurm log files from batch job submissions
  checkpoints/
    <prefix>_<#>.checkpoint     checkpoint file(s) for each job step, named 
                                with the convention: 
                                <prefix>.sbatch == <prefix>_<#>.checkpoint
                                created upon job completion, where # 
                                corresponds to array index of <prefix> job step

Temporary directories:
  <prefix>_tmp                  temporary directory for a given job step

Direct any questions to Kelly DeWeese (kdeweese@mac.com)
"
    exit 0
fi

# Configure pipeline
# Main log file
pipeline_log="queen.log"
# Main pipeline config file
pipeline_config="pipeline.conf"
# User-defined input config file
user_input_config="user_input.conf"
# File created by pipeline after parsing input genome filename
genome_config="genome.conf"
# Date format for output
date_fmt="%-I:%M:%S %p (%a %d %b %Y)"
{
    echo
    echo "----------------------------PIPELINE START----------------------------"
    date +"$date_fmt"
    echo
} >> "$pipeline_log"

# Check if scripts directory specified as argument to script
if [[ -n "$1" ]]
then
    scripts_dir="$1"
else
    # Default is git name
    scripts_dir="s-latissima-popgen"
fi
# If scripts directory exists, change to realpath and append '/' to name
if [[ -d "$scripts_dir" ]]
then
    scripts_dir="$(realpath -e "$scripts_dir")"
    scripts_dir="$scripts_dir/"
    echo "Path to scripts: $scripts_dir" >> "$pipeline_log"
    # Prepend scripts path to config filenames
    pipeline_config="$(realpath -e "$scripts_dir/$pipeline_config")"
    user_input_config="$(realpath -e "$scripts_dir/$user_input_config")"
    genome_config="$(realpath -e "$scripts_dir/$genome_config")"
else
    echo "Path to scripts (current directory): $(pwd)" >> "$pipeline_log"
fi
# Attempt to source config files
{
    echo
    echo "Sourcing config files."
    echo "Pipeline config: $pipeline_config"
    echo "User input config: $user_input_config"
    echo
} >> "$pipeline_log"
if [[ -f "$pipeline_config" ]] && [[ -f "$user_input_config" ]]
then
    source "$pipeline_config"
    source "$user_input_config"
else
    echo "Error - verify config file paths." >> "$pipeline_log"
    exit 1
fi

# Report wait time to user
if (( $(( sleep_time / 60 )) < 1 ))
then
    st="$(( sleep_time / 60 )) second(s)"
elif (( $(( sleep_time / 3600 )) > 1 ))
then
    hr="$(( sleep_time / 3660 ))"
    min="$(( (sleep_time - (hr * 3600)) / 60 ))"
    st="$hr hour(s) and $min minute(s)"
else
    st="$(( sleep_time / 60 )) minute(s)"
fi
{
    echo "Wait time between checking for checkpoints set to: $st"
    echo
} >> "$pipeline_log"

# Validate and parse user-defined variables
# If genome file exists, change name to realpath
if [[ -f "$genome" ]] 
then
    genome="$(realpath -e "$genome")"
else
    echo "Genome file ($genome) not found." >> "$pipeline_log"
    exit 1
fi
# If path to raw reads exists, change name to realpath
if [[ -d "$raw_reads_dir" ]]
then
    raw_reads_dir="$(realpath -e "$raw_reads_dir")"
else
    echo "Reads directory ($raw_reads_dir) not found." >> "$pipeline_log"
    exit 1
fi

# # Count of samples assumes paired-end FASTQs
# num_fastqs="$(find "$raw_reads_dir" -mindepth 2 -maxdepth 2 \
#     -type f -name "*.fastq.gz" -exec realpath -e {} \; | wc -l)"
# num_samples="$(( num_fastqs / 2 ))"

# Configure genome filenames for consistent references
# Parse input genome filename
genome_basename="$(basename "$genome")"
genome_base="${genome_basename%%.*}"
genome_basename_unzip="${genome_basename%%.gz}"
genome_local="$bams_dir/$genome_basename"
genome_local_unzip="$bams_dir/$genome_basename_unzip"
genome_dict="$bams_dir/$genome_base.dict"
genome_idx="$bams_dir/$genome_basename_unzip.fai"
ht2_idx="$bams_dir/$genome_base"
# Write the derived config for downstream steps
cat > "$genome_config" <<EOF
# Generated at "$(date +"$date_fmt")"
genome="$genome"
genome_base="$genome_base"
genome_local="$genome_local"
genome_local_unzip="$genome_local_unzip"
genome_dict="$genome_dict"
genome_idx="$genome_idx"
ht2_idx="$ht2_idx"
EOF

# Functions
# Define function to create log directory from prefix and return directory name
make_logdir () {
    # Create log directory (if needed) from given prefix
    local logdir
    logdir="${1}_logs"
    mkdir -p "$logdir"
    echo "$logdir"
}
# Define function to list checkpoint files based on given prefix
ls_check () {
    local prefix
    prefix="$1"
    if [[ -z "$prefix" ]]
    then
        {
            date +"$date_fmt"
            echo "Error - no prefix given to 'ls_check'."
        } >> "$pipeline_log"
        exit 1
    fi
    find checkpoints -type f -name "$prefix*.checkpoint"
}
# Define function to check for and remove checkpoint files with same prefix
rm_check () {
    local prefix
    prefix="$1"
    if [[ -z "$prefix" ]]
    then
        {
            date +"$date_fmt"
            echo "Error - no prefix given to 'rm_check'."
        } >> "$pipeline_log"
        exit 1
    fi
    find checkpoints -type f -name "$prefix*.checkpoint" -delete
}
# Define function to check for checkpoint files by prefix and
# return string of missing array indices
miss_check () {
    local prefix
    local array_size
    prefix="$1"
    array_size="$2"
    if [[ $# -ne 2 ]]
    then
        {
            date +"$date_fmt"
            echo "Error - 'miss_check' expected 2 arguments but received $#."
            echo "Arguments: $*"
        } >> "$pipeline_log"
        exit 1
    fi
    if [[ -n "$(ls_check "$prefix")" ]]
    then
        for i in $(seq "$array_size")
        do
            if [[ ! -f "checkpoints/${prefix}_$i.checkpoint" ]]
            then
                printf "%s," "$i"
            fi
        done
    else
        echo "Error - no checkpoints found for step: $prefix" >> "$pipeline_log"
        exit 1
    fi
}
# Define function to run an array job step with a set number of 
# checkpoints files as a "dependency" (e.g., wait steps)
# (This avoids QOSMax errors from SLURM with next to zero use of storage)
pipeliner () {
    local array_size
    local prefix
    local step_args
    local sbatch_file
    local logdir
    local logfile
    local num_checks
    local array_indices
    local array_flag
    local cmd

    # Parse arguments to function
    array_size="$1"
    prefix="$2"
    step_args=( "$prefix" "$genome_config" "${@:3}" )

    # Log call to function
    echo "pipeliner $*" >> "$pipeline_log"
    
    # Name sbatch file from prefix
    sbatch_file="${scripts_dir}$prefix.sbatch"

    # Name log file(s) based on array size
    if (( array_size > 1 ))
    then
        # Create log directory named after prefix
        logdir="$(make_logdir "$prefix")"
        logfile="$logdir/%x_%a.log"
    else
        logfile="%x.log"
    fi

    # Check for any existing checkpoints for prefix
    if [[ -n "$(ls_check "$prefix")" ]]
    then
        num_checks="$(ls_check "$prefix" | wc -l)"
        echo "$num_checks checkpoint(s) detected for $prefix" >> "$pipeline_log"
        if [[ "$num_checks" -eq "$array_size" ]]
        then
            echo "$prefix step already run. Skipping." >> "$pipeline_log"
            return 0
        elif (( array_size > 1 ))
        then
            # Use missing checkpoints to set array indices for submission
            array_indices="$(miss_check "$prefix" "$array_size")"
            array_flag="--array=$array_indices"
            {
                echo "Missing checkpoints for $prefix step. Restarting."
                echo "Submitting job array indices: $array_indices"
            } >> "$pipeline_log"
        else
            echo "Error - check inputs to 'pipeliner'." >> "$pipeline_log"
            return 1
        fi
    else
        if (( array_size > 1 ))
        then
            array_flag="--array=1-$array_size"
        fi
        echo "Beginning $prefix step." >> "$pipeline_log"
    fi
    # Job submission
    cmd=(
        sbatch
        --parsable
        -p "$partition"
        -J "$prefix"
        "$array_flag"
        -o "$logfile"
        "$sbatch_file"
        "${step_args[@]}"
    )
    echo "${cmd[*]}" >> "$pipeline_log"
    jobid="$("${cmd[@]}")"
    echo "Submitted batch job $jobid" >> "$pipeline_log"
}

# Run pipeline
# Define associative array containing arguments to each step of pipeline
PIPELINE_STEPS=(
#   [#_step]="<prefix>|[--array]|<input_dir>|<output_dir>|[index_file]|[extra_args]"
  "prep_ref|$bams_dir|$bams_dir"
  "rename|$raw_reads_dir|$samples_dir|$samples_list|$scripts_dir"
  "fastqc|--array|$samples_dir|$qc_dir|$samples_list"
  "trim_galore|--array|$samples_dir|$trimmed_dir|$samples_list|$qc_dir"
  "build_hisat2|$bams_dir|$bams_dir"
  "hisat2|--array|$trimmed_dir|$bams_dir|$samples_list|$qc_dir|$indiv_list"
  "validate_sams|--array|$bams_dir|$qc_dir|$samples_list|.sorted.bam"
  "collect_alignment_summary_metrics|--array|$bams_dir|$qc_dir|$samples_list"
  "collect_wgs_metrics|--array|$bams_dir|$qc_dir|$samples_list"
  "mark_dupes|--array|$bams_dir|$bams_dir|$samples_list|$qc_dir"
  "validate_sams|--array|$bams_dir|$qc_dir|$samples_list|.marked.sorted.bam"
  "collapse_bams|--array|$bams_dir|$bams_dir|$indiv_list"
  "validate_sams|--array|$bams_dir|$qc_dir|$indiv_list|.merged.marked.sorted.bam"
  "index_bams|--array|$bams_dir|$bams_dir|$indiv_list"
  "haplotype_caller|--array|$bams_dir|$gvcfs_dir|$indiv_list"
  "validate_variants|--array|$gvcfs_dir|$qc_dir|$gvcf_list"
  "split_intervals|$split_intervals_dir|$split_intervals_dir|$intervals_list|$scatter"
  "genomicsdbimport|--array|$gvcfs_dir|$genomicsdbimport_dir|$intervals_list|$gvcf_list"
  "genotype_gvcfs|--array|$gvcfs_dir|$vcfs_dir|$indiv_list"
  "sort_vcf|--array|$vcfs_dir|$vcfs_dir|$vcf_list"
  "validate_variants|--array|$vcfs_dir|$qc_dir|$vcf_list"
  "merge_vcfs|$vcfs_dir|$vcfs_dir|$vcf_list"
  "multiqc|$qc_dir|$qc_dir|$scripts_dir"
)

for step in "${!PIPELINE_STEPS[@]}"
do
    # Wait to submit next step until previous completes
    if [[ -n "$dep_prefix" ]] && [[ -n "$dep_size" ]]
    then
        # Compare dependency array size to count of checkpoint files
        until [[ "$(ls_check "$dep_prefix" | wc -l)" -eq "$dep_size" ]]
        do
            {
                date +"$date_fmt"
                echo "Waiting $st for completion of $dep_prefix step."
            } >> "$pipeline_log"
            sleep "$sleep_time"
        done
        # After hisat2 step: sort individual ID list
        if [[ "$dep_prefix" = "hisat2" ]] && [[ -f "$indiv_list" ]]
        then
            echo "Sorting $indiv_list for unique invidual IDs." >> "$pipeline_log"
            sort -u "$indiv_list" > "${indiv_list}_sorted"
            mv "${indiv_list}_sorted" "$indiv_list"
        elif [[ "$dep_prefix" = "hisat2" ]] && [[ ! -f "$indiv_list" ]]
        then
            echo "Error - invidual ID list ($indiv_list) not found." >> "$pipeline_log"
            exit 1
        fi
        # After haplotype_caller step: create gVCF list
        if [[ "$dep_prefix" = "haplotype_caller" ]]
        then
            echo "Creating list of gVCFs: $gvcf_list" >> "$pipeline_log"
            find "$gvcfs_dir" -type f -name "*$genome_base.g.vcf.gz" > "$gvcf_list"
            if [[ "$(wc -l < "$gvcf_list")" -ne "$dep_size" ]]
            then
                echo "Error - incorrect # files in $gvcf_list" >> "$pipeline_log"
                exit 1
            fi
        fi
        # After genotype_gvcfs step: create VCF list
        if [[ "$dep_prefix" = "genotype_gvcfs" ]]
        then
            echo "Creating list of VCF files: $vcf_list" >> "$pipeline_log"
            find "$vcfs_dir" -type f -name "*$genome_base.vcf.gz" > "$vcf_list"
            if [[ "$(wc -l < "$vcf_list")" -ne "$dep_size" ]]
            then
                echo "Error - incorrect # files in $vcf_list"  >> "$pipeline_log"
                exit 1
            fi
        fi
        # After sort_vcf step: overwrite VCF list
        if [[ "$dep_prefix" = "sort_vcf" ]]
        then
            echo "Overwritting VCF list: $vcf_list" >> "$pipeline_log"
            find "$vcfs_dir" -type f -name "*$genome_base.sorted.vcf.gz" > "$vcf_list"
            if [[ "$(wc -l < "$vcf_list")" -ne "$dep_size" ]]
            then
                echo "Error - incorrect # files in $vcf_list" >> "$pipeline_log"
                exit 1
            fi
        fi
    fi

    # Convert stored string into array from separator
    IFS="|" read -r -a args <<< "${PIPELINE_STEPS[$step]}"

    # Log step
    prefix="${args[0]}"
    {
        date +"$date_fmt"
        echo "Running step #$step: $prefix"
    } >> "$pipeline_log"

    # Parse batch array jobs
    if [[ "${args[1]}" = "--array" ]]
    then
        # Set array size based on index file length
        index_file="${args[4]}"
        if [[ -f "$index_file" ]]
        then
            array_size="$(wc -l < "$index_file")"
            args=( "$prefix" "${args[@]:2}" )
        else
            echo "Error - index file ($index_file) not found."  >> "$pipeline_log"
            exit 1
        fi
    else
        # Set array size
        array_size=1
    fi
    echo "Array size set to: $array_size" >> "$pipeline_log"

    # Run pipeline step
    pipeliner "$array_size" "${args[@]}"

    # Update dependency info for next step
    dep_prefix="$prefix"
    dep_size="$array_size"
    
    echo >> "$pipeline_log"
done








# # Rename reads and create $samples_list
# input_sbatch="${scripts_dir}rename.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# # Before running, check if run has already succeeded
# if [[ -f "$samples_list" ]] && [[ -n "$(ls_check "$input_prefix")" ]]
# then
#     {
#         date
#         echo "Checkpoint and samples file ($samples_list) detected."
#         echo "Skipping step: $input_prefix"
#     } >> "$pipeline_log"
# else
#     rm_check "$input_prefix"
#     {
#         date >> "$pipeline_log" 
#         echo "Copying FASTQs from: $raw_reads_dir"
#         echo "Renamed FASTQs will be in: $samples_dir"
#     } >> "$pipeline_log"
#     jobid="$(no_depend "$input_sbatch" "$input_prefix" "$raw_reads_dir" \
#         "$samples_dir" "$samples_list" "$scripts_dir")"
# fi
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # # Remove original renamed reads to conserve memory before next steps
# # # Depend start upon last job step
# # dependency_prefix="$input_prefix"
# # input_prefix="og_reads_deleted"
# # if [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# # then
# #     if [[ -n "$(ls_check "$prefix")" ]]
# #     then
# #         { 
# #             date
# #             echo "Renamed reads already removed. Skipping."
# #         } >> "$pipeline_log"
# #     else    
# #         { 
# #             date
# #             echo "Removing renamed reads to conserve memory before next steps."
# #         } >> "$pipeline_log"
# #         while IFS= read -r sample_id
# #         do
# #             if [[ -f "$samples_dir/${sample_id}_R1.fastq.gz" ]] && \
# #                [[ -f "$samples_dir/${sample_id}_R2.fastq.gz" ]] && \
# #                [[ -f "$trimmed_dir/${sample_id}_R1.repaired.fastq.gz" ]] && \
# #                [[ -f "$trimmed_dir/${sample_id}_R2.repaired.fastq.gz" ]]
# #             then
# #                 rm "$samples_dir/${sample_id}_R1.fastq.gz"
# #                 rm "$samples_dir/${sample_id}_R2.fastq.gz"
# #             else
# #                 {
# #                     date
# #                     echo "Error - some reads missing for ${sample_id}."
# #                     echo "No checkpoint file detected for step: $input_prefix"
# #                 } >> "$pipeline_log"
# #                 exit 1
# #             fi
# #         done < "$samples_list"
# #         touch "checkpoints/${input_prefix}.checkpoint"
# #     fi
# # fi
# # echo >> "$pipeline_log"

# # FastQC
# # Keep previous dependency
# dependency_prefix="$input_prefix"
# dependency="$jobid"
# input_sbatch="${scripts_dir}fastqc.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# # Check for dependency jobid
# if [[ -n "$dependency" ]]
# then
#     {
#         date
#         echo "Running $input_prefix after $dependency_prefix step"
#         echo "($dependency_prefix job ID: $dependency)"
#     } >> "$pipeline_log"
#     jobid="$(depend --array "$array_size" \
#         "$input_sbatch" "$input_prefix" "$dependency" \
#         "$samples_dir" "$qc_dir" \
#         "$samples_list")"
# else
#     # If dependency is finished running, verify its checkpoint
#     jobid="$(pipeliner --array "$array_size" \
#         "$dependency_prefix" $dependency_size \
#         "$sleep_time" "$input_sbatch" "$input_prefix" \
#         "$samples_dir" "$qc_dir" \
#         "$samples_list")"
# fi
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Quality and adapter trimming
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}trim_galore.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" $dependency_size \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$samples_dir" "$qc_dir" \
#     "$samples_list" "$trimmed_dir")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run HISAT2-build on genome
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}build_hisat2.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner \
#     "$dependency_prefix" $dependency_size \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome")"
# dependency_size=1
# echo >> "$pipeline_log"

# # Redefine $genome location after HISAT2-build step
# if [[ -f "$bams_dir/$genome_basename_unzip" ]]
# then
#     genome="$bams_dir/$genome_basename_unzip"
#     {
#         date
#         echo "Genome now being sourced from: $genome"
#     } >> "$pipeline_log"
# else
#     {
#         date
#         echo "Error - gunzipped genome not detected in $bams_dir"
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Run HISAT2 on all samples
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}hisat2.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$trimmed_dir" "$bams_dir" \
#     "$genome" "$samples_list" "$qc_dir" "$indiv_list")"
# dependency_size="$array_size"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Sort IDs in $indiv_list for unique invidual IDs
# dependency_prefix="$input_prefix"
# until [[ -f "$indiv_list" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     date >> "$pipeline_log"
#     echo "Waiting for completion of $dependency_prefix step." >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# if [[ -f "$indiv_list" ]]
# then
#     date
#     echo "Sorting $indiv_list for unique invidual IDs." >> "$pipeline_log"
#     sort -u "$indiv_list" > "${indiv_list}_sorted"
#     mv "${indiv_list}_sorted" "$indiv_list"
# else
#     {
#         date
#         echo "Error - invidual ID file ($indiv_list) not detected."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Create reference genome dictionary and 
# # samtools index of genome for GATK tools
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}prep_ref.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # Run GATK4 ValidateSamFile on HISAT2 alignmnet BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_sams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# pattern=".sorted.bam"
# iteration=1
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_list" "$pattern")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 CollectAlignmentSummaryMetrics 
# # on HISAT2 alignmnet BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}collect_alignment_summary_metrics.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 CollectWgsMetrics on HISAT2 alignmnet BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}collect_wgs_metrics.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_list")"
# echo >> "$pipeline_log"

# # Run GATK4 MarkDuplicates
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}mark_dupes.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome" "$samples_list" "$qc_dir")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 ValidateSamFile on MarkDuplicate BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_sams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# pattern=".marked.sorted.bam"
# iteration=2
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$samples_list" "$pattern")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Set new array size to number of individuals
# if [[ -f "$indiv_list" ]]
# then
#     num_indiv="$(wc -l < "$indiv_list")"
#     array_size="$num_indiv"
#     {
#         date
#         echo "Array size set to ${array_size}."
#     } >> "$pipeline_log"
# else
#     { 
#         date
#         echo "Error - invidual ID file ($indiv_list) not detected."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Collapse BAMs per sample into BAMs per individual with GATK4 MergeSamFiles
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}collapse_bams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome" "$indiv_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 ValidateSamFile on MarkDuplicate BAMs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_sams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# pattern=".merged.marked.sorted.bam"
# iteration=3
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$qc_dir" \
#     "$genome" "$indiv_list" "$pattern")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Index collapsed BAMs for GATK4 HaplotypeCaller
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}index_bams.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$bams_dir" \
#     "$genome" "$indiv_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 HaplotypeCaller
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}haplotype_caller.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$bams_dir" "$gvcfs_dir" \
#     "$genome" "$indiv_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Create file to index HaplotypeCaller gVCFs
# dependency_prefix="$input_prefix"
# until [[ -d "$gvcfs_dir" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     date >> "$pipeline_log"
#     echo "Waiting for completion of $dependency_prefix step." >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# num_gvcfs="$(find "$gvcfs_dir" -type f -name "*.g.vcf.gz" | wc -l)"
# if [[ "$num_gvcfs" -eq "$array_size" ]]
# then
#     {
#         date
#         echo "Creating $gvcf_list of $num_gvcfs files."
#     } >> "$pipeline_log"
#     find "$gvcfs_dir" -type f -name "*.g.vcf.gz" > "$gvcf_list"
#     num_gvcfs_list="$(wc -l < "$gvcf_list")"
#     if [[ $num_gvcfs_list -ne $array_size ]]
#     then
#         {
#             date
#             echo "Error - incorrect # files ($num_gvcfs_list/$array_size) in $gvcf_list"
#             echo "Exiting..."
#         } >> "$pipeline_log"
#         exit 1
#     fi
# else
#     {
#         date
#         echo "Error - incorrect # files ($num_gvcfs/$array_size) in $gvcfs_dir"
#         echo "$gvcf_list not created. Exiting..."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Run GATK4 ValidateVariants on HaplotypeCaller gVCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_variants.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# iteration=1
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$gvcfs_dir" "$qc_dir" \
#     "$genome" "$gvcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 SplitIntervals on genome to produce interval 
# # lists in $split_intervals_dir for CombineGVCFs step
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}split_intervals.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$split_intervals_dir" "$split_intervals_dir" \
#     "$genome" "$scatter")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # Set array size to number of split interval lists created
# dependency_prefix="$input_prefix"
# until [[ -d "$split_intervals_dir" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     {
#         date
#         echo "Waiting for completion of $dependency_prefix step."
#     } >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# array_size="$(find "$split_intervals_dir" -type f -name "*.list" | wc -l)"
# {
#     date
#     echo "Array size set to number of split interval lists ($array_size) created
#     by split_intervals step (not necessarily equal to scatter=$scatter because
# --subdivision-mode BALANCING_WITHOUT_INTERVAL_SUBDIVISION)."
# } >> "$pipeline_log"
# # Create file to index split intervals lists
# find "$split_intervals_dir" -type f -name "*.list" > "$intervals_list"
# echo >> "$pipeline_log"

# # Run GATK4 GenomicsDBImport
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}genomicsdbimport.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$gvcfs_dir" "$genomicsdbimport_dir" \
#     "$genome" "$intervals_list" "$gvcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 GenotypeGVCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}genotype_gvcfs.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$genomicsdbimport_dir" "$vcfs_dir" \
#     "$genome")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Create list of GenotypeGVCFs VCFs
# dependency_prefix="$input_prefix"
# until [[ -d "$vcfs_dir" ]] && \
#       [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     {
#         date
#         echo "Waiting for completion of $dependency_prefix step."
#     } >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# num_vcfs="$(find $vcfs_dir -type f -name "*${genome_base}.vcf.gz" | wc -l)"
# if [[ "$num_vcfs" -eq "$array_size" ]]
# then
#     {
#         date
#         echo "Creating $vcf_list of $num_vcfs files."
#     } >> "$pipeline_log"
#     find $vcfs_dir -type f -name "*${genome_base}.vcf.gz" > "$vcf_list"
#     num_vcfs_list="$(wc -l < "$vcf_list")"
#     if [[ "$num_vcfs_list" -ne "$array_size" ]]
#     then
        
#         {
#             date
#             echo "Error - incorrect # files ($num_vcfs_list/$array_size) in $vcf_list" 
#             echo "Exiting..."
#         } >> "$pipeline_log"
#         exit 1
#     fi
# else
#     {
#         date
#         echo "Error - incorrect # files ($num_vcfs/$array_size) in $vcfs_dir"
#         echo "$vcf_list not updated. Exiting..."
#     } >> "$pipeline_log"
#     exit 1
# fi
# echo >> "$pipeline_log"

# # Run GATK4 SortVcf on GenotypeGVCFs VCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}sort_vcf.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$vcfs_dir" "$qc_dir" \
#     "$genome" "$vcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Overwrite index of VCF files with sorted index
# # Depend start upon last job step
# dependency_prefix="$input_prefix"
# until [[ "$(ls_check "$prefix" | wc -l)" -eq "$dependency_size" ]]
# do
#     {
#         date
#         echo "Waiting for completion of $dependency_prefix step."
#     } >> "$pipeline_log"
#     sleep "$sleep_time"
# done
# num_vcfs="$(find $vcfs_dir -type f -name "*${genome_base}sorted.vcf.gz" | wc -l)"
# if [[ "$num_vcfs" -eq "$array_size" ]]
# then
#     {
#         date
#         echo "Creating $vcf_list of $num_vcfs files."
#     } >> "$pipeline_log"
#     ls "$vcfs_dir/"*"${genome_base}.sorted.vcf.gz" > "$vcf_list"
#     num_vcfs_list="$(wc -l < "$vcf_list")"
#     if [[ "$num_vcfs_list" -ne "$array_size" ]]
#     then
#         {
#             date
#             echo "Error - incorrect # files ($num_vcfs_list/$array_size) in $vcf_list"
#             echo "Exiting..."
#         } >> "$pipeline_log"
#         exit 1
#     fi
# else
#     {
#         date
#         echo "Error - incorrect # files ($num_vcfs/$array_size) in $vcfs_dir"
#         echo "$vcf_list not updated. Exiting..."
#     } >> "$pipeline_log"
# fi
# echo >> "$pipeline_log"

# # Run GATK4 ValidateVariants on GenotypeGVCFs VCFs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}validate_variants.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# iteration=2
# input_prefix="${input_prefix}_${iteration}"
# jobid="$(pipeliner --array "$array_size" \
#     "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$vcfs_dir" "$qc_dir" \
#     "$genome" "$vcf_list")"
# # Set dependency size for next step
# dependency_size="$array_size"
# echo >> "$pipeline_log"

# # Run GATK4 MergeVcfs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}merge_vcfs.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$vcfs_dir" "$genome" "$vcf_list")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

# # Run MultiQC on pipeline QC outputs
# # Depend start upon last job step
# dependency="$jobid"
# dependency_prefix="$input_prefix"
# input_sbatch="${scripts_dir}multiqc.sbatch"
# input_prefix="$(get_prefix "$input_sbatch")"
# if [[ -n "$dependency" ]]
# then
#     {
#         date
#         echo "Running $input_prefix after $dependency_prefix step (jobid: $dependency)" 
#     } >> "$pipeline_log"
#     jobid="$(depend "$input_sbatch" "$input_prefix" \
#         "$dependency" \
#         "$qc_dir")"
# fi
# jobid="$(pipeliner "$dependency_prefix" "$dependency_size" \
#     "$sleep_time" "$input_sbatch" "$input_prefix" \
#     "$qc_dir")"
# # Set dependency size for next step
# dependency_size=1
# echo >> "$pipeline_log"

