#!/bin/bash
#SBATCH --time=3-0
#SBATCH -J queen
#SBATCH -o %x.log

## Variant calling pipeline
# A SLURM- and conda-dependent pipeline with sequential job steps linked by 
# dependencies and checkpoint files

# Help message
if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]
then
    echo "\
----------------------WELCOME TO VARIANT CALLING PIPELINER----------------------

Usage: 
  bash/sbatch pipeline-s-latissima-popgen.sh [scripts_dir]

Options:
  -h/--help                      print this usage message

Note: Sourced SBATCH files named with convention: <prefix>.sbatch 

Takes as input a genome and PATH to a directory containing FASTQs to align, and
outputs...

Analysis:
  indexer/
    samples_list.txt             indexes sample IDs
    individuals_file.txt         indexes individual IDs
    intervals_list.txt           indexes split interval lists
    gvcf.list                    indexes gVCF files 
    vcf.list                     indexes VCF files (in numerical order)
  wgs/                        
    *.fastq.gz                   FASTQ files renamed to shorter sample IDs 
                                 (copied from source)
    *.repaired.fastq.gz          FASTQ read pairs repaired with repair.sh
  trimmed_reads/
    *_val_1/2.fq.gz              reads post trimming by Trim Galore!
  bams/
    *.fasta                      reference genome (copied from source)
    *.fasta.ht2                  indexed reference genome
    *.fasta.fai                  samtools-indexed reference genome
    *.dict                       GATK4-style reference genome dictionary
    *.sorted.bam                 sorted alignment files of trimmed reads to 
                                 reference genome
    *.sorted.marked.bam          sorted alignment files, duplicates marked
    *.sorted.marked.merged.bam   sorted alignment files, merged by individual
  gvcfs/
    *.g.vcf.gz                   genome variant call files (gVCFs) for each 
                                 individual
  split_intervals/
    *-scattered.interval_list    GATK4-style lists of genomic intervals, split 
                                 into as close to the desired scatter count as 
                                 possible without splitting input reference 
                                 contigs (e.g., scaffolds/chromosomes)
  genomicsdbimport/
    interval_*/                  GATK4-style GenomicsDB (datastore of variant
                                 call data from each individual, split into 
                                 groups of genomic intervals specified in 
                                 *-scattered.interval_list files)
  vcfs/
    *.vcf.gz                     variant call files (VCFs) for each group of 
                                 genomic intervals
  master_{genome_base}.vcf.gz    final VCF file of all samples aligned to the
                                 reference genome

Quality control:
  quality_control/
    *_fastqc.zip/html            FastQC reports for all input FASTQs
    *_val_1/2_fastqc.zip/html    FASTQC reports for trimmed FASTQs
    *_trimming_report.txt        Trim Galore! trimming report for each sample
    *.hisat2.summary             HISAT2 alignment report for each sample
    *.validate.summary           validation reports of alignment (SAM/BAM) and 
                                 variant (gVCF/VCF) files
    multiqc_report.html          MultiQC report summarizing QCs at each step

Logs and checkpoints:
  queen.log                      log file generated by pipeliner script
  <prefix>_logs/
    <prefix>_<#>.out             SLURM log files from inividual job step 
                                 submissions, named with the convention: 
                                 <prefix>.sbatch > 
                                 <prefix>_logs/<prefix>_<#>.out 2>&1
                                 created upon job completion, where #
                                 corresponds to array index of <prefix> job step
  checkpoints/
    <prefix>_<#>.checkpoint      checkpoint file(s) for each job step, named 
                                 with the convention: 
                                 <prefix>.sbatch == <prefix>_<#>.checkpoint
                                 created upon job completion, where # 
                                 corresponds to array index of <prefix> job step

Temporary directories:
  <prefix>_tmp                   temporary directory for a given job step

Direct any questions to Kelly DeWeese (kdeweese@mac.com)
"
    exit 0
fi

# Configure pipeline
# Main log file
pipeline_log="queen.log"
# User-defined config file
config_file="pipeline.conf"
# Check if scripts directory specified in input to script
if [[ -n "$1" ]]
then
    scripts_dir="$1"
else
    scripts_dir="s-latissima-popgen"
fi
# If scripts directory exists, change to realpath and append '/' to name
if [[ -d "$scripts_dir" ]]
then
    scripts_dir="$(realpath -e "$scripts_dir")"
    scripts_dir="$scripts_dir/"
    echo "Path to scripts: ${scripts_dir}..." >> "$pipeline_log"
    # Prepend scripts path to config filename
    config_file="$scripts_dir/$config_file"
else
    echo "Path to scripts (current directory): $(pwd)" >> "$pipeline_log"
fi
# Source config file (if exists)
if [[ -f "$config_file" ]]
then
    echo "Sourcing config file: $config_file"
    source "$config_file"
else
    echo "Error - No config file ($config_file) in scripts path ($scripts_dir)."
    exit 1
fi

# Validate and parse user-defined variables
# If genome file exists, change name to realpath
if [[ -f "$genome" ]] 
then
    genome="$(realpath -e "$genome")"
else
    echo "Genome file $genome not detected." >> "$pipeline_log"
    exit 1
fi
genome_basename="$(basename "$genome")"
genome_basename_unzip="${genome_basename%%.gz}"
genome_base="${genome_basename%%.*}"
# If path to raw reads exists, change name to realpath
if [[ -d "$path_to_raw_reads" ]]
then
    path_to_raw_reads="$(realpath -e "$path_to_raw_reads")"
else
    echo "Reads directory ($path_to_raw_reads) not detected." >> "$pipeline_log"
    exit 1
fi

# Pipeline variables
# Count of samples assumes paired-end FASTQs
num_fastqs="$(find "$path_to_raw_reads" -mindepth 2 -maxdepth 2 \
    -type f -name "*.fastq.gz" -exec realpath -e {} \; | wc -l)"
num_samples="$(( num_fastqs / 2 ))"
# Directory to copy reads into
samples_dir="wgs"
# Directory to write array-indexed lists (e.g., $samples_list)
indexer_dir="indexer"
mkdir -p "$indexer_dir"
# Text file listing sample IDs
samples_list="$indexer_dir/samples_list.txt"
# Directory to write QC output
qc_dir="quality_control"
mkdir -p "$qc_dir"
# Directory to write trimmed read files
trimmed_dir="trimmed_reads"
mkdir -p "$trimmed_dir"
# Directory to write BAM files
bams_dir="bams"
mkdir -p "$bams_dir"
# Text file listing individual IDs
indiv_list="$indexer_dir/individuals_file.txt"
# Directory to write gVCFs
gvcfs_dir="gvcfs"
mkdir -p "$gvcfs_dir"
# Directory to write inverval.list files (output of GATK4's SplitIntervals)
split_intervals_dir="split_intervals"
mkdir -p "$split_intervals_dir"
# Number of interval groups to split into for scatter-gather parallelization
scatter=100
# Text file listing interval.list filenames
intervals_list="$indexer_dir/intervals_list.txt"
# Text file listing gVCF filenames
gvcf_list="$indexer_dir/gvcfs.list"
# Directory to import gVCFs into GenomicsDBs
genomicsdbimport_dir="genomicsdbimport"
mkdir -p "$genomicsdbimport_dir"
# Directory to write genotyped VCFs
vcfs_dir="vcfs"
mkdir -p "$vcfs_dir"
# Text file listing genotyped VCF filenames
vcf_list="$indexer_dir/vcf.list"

# Functions
# Define function to make a log directory from an input prefix
# and return directory name
make_logdir () {
    # Create log directory (if needed) from given prefix
    local logdir
    logdir="${1}_logs"
    mkdir -p "$logdir"
    echo "$logdir"
}
# Define function to run step in pipeline
run_step () {
  local array_indices
  local dependency_prefix
  local dependency_size
  local sleep_time
  local input_sbatch
  local input_prefix
  local trailing_args
  local num_checks
  local array_flag
  local jobid
  # Job submission
  cmd=(
      sbatch
      --parsable
      -p "$partition"
      -J "$prefix"
      --array="$array_size"
      -o "$logdir/%x_%a.out"
      "$sbatch_file"
      "$prefix"
      "${trailing_args[@]}"
  )
  jobid="$("${cmd[@]}")"
  echo "${cmd[*]}" >> "$pipeline_log"
}


declare -A PIPELINE_STEPS=(
  # [step_name]="<prefix> [--array array_size] <input_dir> <output_dir> <genome> [index_file] [extra_args]"
  [rename]="rename $path_to_raw_reads $samples_dir $genome $samples_list $scripts_dir"
  [fastqc]="fastqc --array $array_size $samples_dir $qc_dir $genome $samples_list"
  [trim_galore]="trim_galore --array $array_size $samples_dir $trimmed_dir $samples_list $qc_dir"
  [build_hisat2]="build_hisat2 $bams_dir $bams_dir $genome"
  [hisat2]="hisat2 --array $array_size $trimmed_dir $bams_dir $genome $samples_list $qc_dir $indiv_list"
  [prep_ref]="prep_ref $bams_dir $bams_dir $genome"
  [validate_sams_1]="validate_sams --array $array_size $bams_dir $qc_dir $genome $samples_list .sorted.bam"
  [collect_alignment_summary_metrics]="collect_alignment_summary_metrics --array $array_size $bams_dir $qc_dir $genome $samples_list"
  [collect_wgs_metrics]="collect_wgs_metrics --array $array_size $bams_dir $qc_dir $genome $samples_list"
  [mark_dupes]="mark_dupes --array $array_size $bams_dir $bams_dir $genome $samples_list $qc_dir"
  [validate_sams_2]="validate_sams --array $array_size $bams_dir $qc_dir $genome $samples_list .marked.sorted.bam"
  [collapse_bams]="collapse_bams --array $array_size $bams_dir $bams_dir $genome $indiv_list"
  [validate_sams_3]="validate_sams --array $array_size $bams_dir $qc_dir $genome $indiv_list .merged.marked.sorted.bam"
  [index_bams]="index_bams --array $array_size $bams_dir $bams_dir $genome $indiv_list"
  [haplotype_caller]="haplotype_caller --array $array_size $bams_dir $gvcfs_dir $genome $indiv_list"
  [validate_variants_1]="validate_variants --array $array_size $gvcfs_dir $qc_dir $genome $gvcf_list"
  [split_intervals]="split_intervals $split_intervals_dir $split_intervals_dir $genome $scatter"
  [genomicsdbimport]="genomicsdbimport --array $array_size $gvcfs_dir $genomicsdbimport_dir $genome $intervals_list $gvcf_list"
  [genotype_gvcfs]="genotype_gvcfs --array $array_size $gvcfs_dir $vcfs_dir $genome $indiv_list"
  [sort_vcf]="sort_vcf --array $array_size $vcfs_dir $qc_dir $genome $vcf_list"
  [validate_variants_2]="validate_variants --array $array_size $vcfs_dir $qc_dir $genome $vcf_list"
  [merge_vcfs]="merge_vcfs $vcfs_dir $vcfs_dir $genome $vcf_list"
  [multiqc]="multiqc $qc_dir $scripts_dir"
)
