# User-defined input variables
# Reference genome
genome="/project2/noujdine_61/kdeweese/latissima/Assembly/Assembled_scaffolds__masked_/SlaSLCT1FG3_1_AssemblyScaffolds_Repeatmasked.fasta.gz"
# Path to folder containing raw reads
# Pipeline assumes compressed FASTQs with extension: ".fastq.gz"
raw_reads_dir="/project2/noujdine_61/sugar_kelp_data/FastQ_GZout_Plate1_2_3/"
# Slurm partition for sbatch submissions
partition="main"
# Maximum number of jobs to launch concurrently
max_run=30